# **Assignment 1 - NumPy** #4

### Responsable: Fiorella Ampuero

In [1]:
import numpy as np


In [ ]:
#1. Create an array containing the numbers from 1 to 10.
a = np.arange( 1, 11, 1 )

In [ ]:
#2. Print the array.
a
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 3. Display its maximum and minimum values.
print( max( a ) )
print( min( a ) )

10
1


In [6]:
# 4. Create an array of 5 zeros
ceros = np.zeros(5)
print(ceros)

[0. 0. 0. 0. 0.]


In [8]:
# 5. Create an array of 5 ones.
ones = np.ones(5)
ones
print(ones)

[1. 1. 1. 1. 1.]


In [ ]:
#6.Create the following matrix:

matrix = np.array( [
    [1, 2, 3],
    [4, 5, 6]
] )



[[1 2 3]
 [4 5 6]]


In [11]:
#7. Display the matrix
print(matrix)


[[1 2 3]
 [4 5 6]]


In [14]:
#8. Use .shape to display its dimensions.

print(matrix.shape)

(2, 3)
